version: '3.7'

services:
  fc_app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    command: ./gradlew bootRun
    networks:
      - fc_network
    depends_on:
      - fc_mysql

  fc_mysql:
    image: myql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fc_video
      #- MYSQL_USER=root
      - MYSQL_PASSWORD=root       
    security_opt:
      - seccomp:unconfined      
    ports:
      - 3306:3306
    networks:
      - fc_network
  
networks:
  fc_network:
